config/routes.rb
Rails.application.routes.draw do

  resources :cocktails do 
  	resources :doses, only: [:new, :create]
  	# cocktails/3/doses/new
  	# @dose.cocktail = cocktail that the dose belongs to
  end

  resources :doses, only: :destroy

  root to: 'cocktails#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
	has_many :doses, dependent: :destroy 
	has_many :ingredients, through: :doses

	validates :name, presence: true, uniqueness: true

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  # because it has both ids stored as attributes

  validates :description, uniqueness: { scope: :ingredient}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
	has_many :doses, dependent: :destroy
	has_many :cocktails, through: :doses

	validates :name, presence: true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
  	@cocktails = Cocktail.all
  end

  def show
  	@cocktail = Cocktail.find(params[:id])
  end

  def new
  	# create blank form
  	@cocktail = Cocktail.new
  	# Cocktail(name: nil)
  end

  def create
  	@cocktail = Cocktail.new(cocktail_params)
  	# Cocktail(name: "Some Cocktail Name")
  	if @cocktail.save
  		redirect_to cocktail_path(@cocktail)
  	else
  		render :new
  	end
  end

  def edit
  	@cocktail = Cocktail.find(params[:id])
  end

  def update
  	@cocktail = Cocktail.find(params[:id])
  	@cocktail.update(cocktail_params)
  	if @cocktail.save
  		redirect_to cocktail_path(@cocktail)
  	else
  		render :edit
  	end
  end


  def destroy 
  	@cocktail = Cocktail.find(params[:id])
  	@cocktail.destroy
  	redirect_to cocktails_path
  	# do not have a cocktail, so go to index instead
  end

  def cocktail_params
	params.require(:cocktail).permit(:name)  	
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
  	@dose = Dose.new
  	@cocktail = Cocktail.find(params[:cocktail_id])
  	# Dose.new(description: nil, cocktail_id: nil, ingredient_id: nil)
  end

  def create
  	@dose = Dose.new(dose_params)
  	@cocktail = Cocktail.find(params[:cocktail_id])
  	# Dose.new(description: "slice", cocktail_id: 5, ingredient_id: 2 (from the frontend))
  	@dose.cocktail_id = @cocktail.id
	if @dose.save
		redirect_to cocktail_path(@cocktail)
	else
		render :new
	end 	
  end

  def destroy
  	@dose = Dose.find(params[:id])
  	@cocktail = @dose.cocktail
  	@dose.destroy
  	redirect_to cocktail_path(@cocktail)
  	
  end

  private

  def dose_params
  	params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
				<%= f.input :name, label: "Please enter a name" %>
				<%= f.submit "Submit!", class: "btn btn-warning" %>
<% end %>

app/views/cocktails/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col col-sm-4 col-sm-offset-4">
			<h1>Edit <%= @cocktail.name %></h1>
			<%= render 'form' %>
		</div>
	</div>
</div>

  

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://estcourtnews.co.za/wp-content/uploads/sites/67/2016/12/AA13.jpg');">
  <div class="banner-content">
    <h1>Great Drinks for Driving</h1>
    <p>Take Control. Drink Irresponsibly.</p>
      <div class="row">
        <% @cocktails.each do |cocktail| %>
            <div class="col col-xs-12 col-sm-4">
              <%= link_to cocktail_path(cocktail) do %>
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1499950617211-a8609a16ad72?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=3dd421728e43f418d59662d1a2352358&auto=format&fit=crop&w=2093&q=80');">
                <div class="card-category">Popular</div>
                <div class="card-description">
                  <h2><%= cocktail.name %></h2>
                </div>
              </div>

              <% end %>
            </div>
        <% end %>
          </div>
          <%=link_to "Add a Drink!", new_cocktail_path, class: "btn-medium" %>
        </div>
      </div>
    </div>
	</div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
	<div class="row">
		<div class="col col-sm-4 col-sm-offset-4">
			<h1>Cocktail Submission</h1>
			<%= render 'form' %>
			<% end %>
		</div>
	</div>
</div>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1472245088132-ccd50746725c?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=fa7ad7a324cc9efb65fe1a3abf6c287d&auto=format&fit=crop&w=1949&q=80');">
  <div class="banner-content">
    <h1><%= @cocktail.name %></h1>
<!--     <p>Learn to code with us in Berlin</p>

 --> 
 	<%= link_to "Edit", edit_cocktail_path(@cocktail), class: "btn btn-danger" %>   
 	<%= link_to "Go Back", cocktails_path, class: "btn btn-danger" %>
 	<%= link_to "Delete", cocktail_path(@cocktail), method: :delete, data: {confirm: "Are you sure? Don't you love cocktails?"},  class: "btn btn-danger"%>

 	<p>
 		<%= link_to "add a dose", new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %>
 	</p>
  </div>
</div>

<% @cocktail.doses.each do |dose| %>
	<p><%= dose.description %> (<%= dose.ingredient.name %>) 
		<%= link_to "delete", dose_path(dose), method: :delete%></p>
<% end %>

app/views/doses/new.html.erb
<div class="container">
	<div class="row">
		<div class="col col-sm-4 col-sm-offset-4">
			<h1>Add a new dose to the cocktail</h1>
			<%= simple_form_for ([@cocktail, @dose]) do |f| %>
			<!-- form action="cocktails/5/doses" method="post" -->
				<%= f.input :description, inline_label: "Enter an amount" %>
				<%= f.association :ingredient, collection: Ingredient.all %>
				<%= f.submit "Add a Dose" %>
			<% end %>
			  
			
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>